### PR TITLE
style: add very_good_analysis

### PR DESCRIPTION
**Pull request by lsaudon**
## Status

**READY**

## Breaking Changes

NO

## Description

Add very_good_analysis in mocktail and mocktail_image_network

## Type of Change

- [ ] ✨ New feature (non-breaking change which adds functionality)
- [ ] 🛠️ Bug fix (non-breaking change which fixes an issue)
- [x] ❌ Breaking change (fix or feature that would cause existing functionality to change)
- [x] 🧹 Code refactor
- [ ] ✅ Build configuration change
- [ ] 📝 Documentation
- [x] 🗑️ Chore

### CODE REVIEW

**Comment by felangel** [comment]
This is a duplicate of #154

**Comment by lsaudon** [comment]
Yes, but the PR has not been updated for 23 days for the CI pass.

**Comment by felangel** [comment]
> Yes, but the PR has not been updated for 23 days for the CI pass.

That's because the latest version of Very Good Analysis introduces breaking changes and also forces an upgrade to Dart 2.18

**Comment by lsaudon** [comment]
I reverted the part that created a breaking changes in the package.

**Pull request closed without merging**
