### PR TITLE
chore(mocktail): upgrade dependencies

### LINKED ISSUE #166: Support the latest Analyzer
@felangel 
The current dependency to 
test: ^1.16.0 that rely on an old analyzer version

any plan to upgrade to at least 
test: ^1.21.6

### PR DESCRIPTION
**Pull request by elias8**
## Status

**READY**

## Breaking Changes

NO

## Description

Resolves #166 

## Type of Change

- [ ] ✨ New feature (non-breaking change which adds functionality)
- [ ] 🛠️ Bug fix (non-breaking change which fixes an issue)
- [ ] ❌ Breaking change (fix or feature that would cause existing functionality to change)
- [ ] 🧹 Code refactor
- [ ] ✅ Build configuration change
- [ ] 📝 Documentation
- [x] 🗑️ Chore

### CODE REVIEW

**Review by felangel — CHANGES_REQUESTED** [review]
Why are these changes necessary? The original constraints allow for the latest versions of each of the dependencies so these changes should not be needed imo.

**Comment by elias8** [comment]
Commented and attached a sample error [here](https://github.com/felangel/mocktail/issues/166#issuecomment-1328118606). I think the main issue is from dependencies that I have in my project that rely on a different version of `test_api`.

**Comment by felangel** [comment]
> Commented and attached a sample error [here](https://github.com/felangel/mocktail/issues/166#issuecomment-1328118606). I think the main issue is from dependencies that I have in my project that rely on a different version of `test_api`.

It looks like a duplicate of https://github.com/flutter/flutter/issues/115284. Did you verify that your changes resolve the issue? I don’t think the changes in this PR will have any impact because at the end of the day the version constraints should allow for the latest versions of each of these packages.

**Comment by elias8** [comment]
Tried to verify it now and it doesn't actually fix it. Saw your comment on the flutter/flutter#115284 and curious if that fix has landed on the stable channel that was released a few days ago.

**Comment by elias8** [comment]
I tried to verify it now, and it doesn't fix it. And I saw your comment on flutter/flutter/issues#115284 and am curious if that fix has landed on the stable channel that was released a few days ago. 

Thanks for the quick response!

**Comment by felangel** [comment]
> I tried to verify it now, and it doesn't fix it. And I saw your comment on flutter/flutter/issues#115284 and am curious if that fix has landed on the stable channel that was released a few days ago.
> 
> Thanks for the quick response!

No problem! Going to close this for now since the associated changes don’t resolve the issue, thanks!

**Pull request closed without merging**
